# Generated by Django 4.2.8 on 2023-12-24 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_payments_date_payments_alter_payments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_payments',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 13, 23, 20, 288551), verbose_name='дата оплаты'),
        ),
    ]
