# Generated by Django 4.2.8 on 2023-12-24 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payments_date_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_payments',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 13, 24, 56, 647167), verbose_name='дата оплаты'),
        ),
    ]
