# Generated by Django 4.2.8 on 2023-12-24 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payments_date_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_payments',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 13, 40, 59, 507674), verbose_name='дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
    ]
