# Generated by Django 4.2.8 on 2023-12-24 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payments_payment_link_alter_payments_date_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_payments',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 15, 0, 27, 777400), verbose_name='дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Сылка на оплату'),
        ),
    ]
