# Generated by Django 4.2.8 on 2023-12-25 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_payments_date_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_payments',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 7, 32, 24, 535398), verbose_name='дата оплаты'),
        ),
    ]
