# Generated by Django 4.2.8 on 2023-12-25 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_payments_date_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_payments',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 11, 45, 32, 434552), verbose_name='дата оплаты'),
        ),
    ]
